version: '3.8'

services:
  web:
    build: ./
    command: gunicorn -c gunicorn.conf.py myproject.wsgi:application
    expose:
      - 8003
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
    volumes:
      - static_volume:/home/helpdesk/web/staticfiles
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=helpdesk_test
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/helpdesk/web/staticfiles
    ports:
      - 1337:8003
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
